version: '3.8'
services:
  postgres:
    platform: linux/arm64/v8 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: burritoer
      POSTGRES_PASSWORD: very_strong_password
      POSTGRES_DB: burrito-shop
    volumes:
      - postgres:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
volumes:
  postgres: